services:
  - type: web
    name: api-resumo-spacy
    runtime: python
    buildCommand: "pip install -r requirements.txt && python -m spacy download pt_core_news_sm"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
